version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: cimg/clojure:1.12-openjdk-21.0
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test
      - run: lein cloverage --codecov
      - run: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
